name: Pierwszy workflow

on: [push]

jobs:
  pierwszy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: echo Hello World
      - run: ls
      - run: pwd
      - run: whoami
  drugi-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, World from second job
  trzeci-job:
    runs-on: ubuntu-latest
    needs: [drugi-job]
    steps:
      - run: echo Hello, World from third job
