name: Pierwszy workflow

on: [push]

jobs:
  pierwszy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - run: echo Hello World
      - run: ls
      - run: pwd
      - run: whoami
